### ISSUE TITLE
Custom Step Results

### ISSUE THREAD

**Issue by pmagnuson** [theRealGetman/survey-flow#3]
I'm really liking the SurveyFlow package. 

I have written a custom SurveyStep and with the associated Widget.  

The CustomStepWidget is a custom Material Slider.  When the step completes how does the custom Widget add to the Survey results?

**Comment by thebedcoder** [comment]
Hey @pmagnuson 
I really appreciate that you like this package 😊

Can you show me the code? It would be easier to understand what is needed.

**Comment by thebedcoder** [comment]
In the example CustomStepWidget has onPressed that is **ButtonPressedCallback**. You can pass results using this callback.
